---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.10
  - 2.3.3
  - 2.5.5
cache:
  - bundler
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
env:
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.5" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
  - PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
